version: '3.0'
services:
    course-mysql:
        image: mysql:latest
        command: --max_allowed_packet=52505856 --bulk_insert_buffer_size=52505856
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=shacourse
            - MYSQL_USER=demo
            - MYSQL_PASSWORD=demo
        ports:
            - 3306:3306
        container_name: mysql    
    cassandra:
        #build: ./cassandra
        image: royjoydeep1/cassandra:latest
        ports:
            - 9042:9042
        container_name: cassandra
    discovery-service:
        #build: ./eureka-discovery-service  
        #entrypoint: /wait-for-it.sh -t 5000 mysql:3306 -- java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        image: royjoydeep1/eureka-discovery-service:latest
        ports:
            - 8761:8761
           
    user-service:
        #build: ./microservice-user-management
        #wait until mysql changesets are implemented. Then call app.jar
        #entrypoint: /wait-for-it.sh discovery-service:8761 -- java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        image: royjoydeep1/microservice-user-management:latest
        depends_on:
            - discovery-service        
        links:
          - course-mysql:mysql
        ports:
          - 8000:8000          
    log-service:
        #build: ./microservice-log-management
        image: royjoydeep1/microservice-log-management:latest
        environment:
            SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra        
        #entrypoint: /wait-for-it.sh cassandra:9042 -- java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        depends_on:
            - discovery-service
            - cassandra
        ports:
            - 8002:8002  
    course-service:
        #build: ./microservice-course-management
        #entrypoint: /wait-for-it.sh user-service:8000 -- java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        image: royjoydeep1/microservice-course-management:latest
        depends_on:
            - discovery-service
            - user-service
            - log-service
            - course-mysql
        ports:
            - 8001:8001 
    gateway-service:
        #build: ./zuul-gateway-service
        #entrypoint: /wait-for-it.sh course-service:8001 -- java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        image: royjoydeep1/zuul-gateway-service:latest
        depends_on:
            - discovery-service
            - user-service
            - log-service
            - course-service
        ports:
            - 8765:8765 
    course-client:
        #build: ./course-enrollment-client
        image: royjoydeep1/course-enrollment-client:latest
        ports:
            - 4200:80            
            
networks:
  default:
    driver: bridge