spring:
  profiles: container
    
server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false